### ISSUE TITLE
[feat] 링크샵 리스트페이지 로고 추가

### ISSUE THREAD

**Issue by April-37** [Team4LinkShop/Team4LinkShop#4]
- '로고' 버튼을 클릭하면 “/list” 페이지로 이동합니다.(새로고침)
<img width="800" alt="화면 캡처 2024-09-25 185347" src="https://github.com/user-attachments/assets/35f7f4fc-c4bc-43f6-bf2d-5e45e4f609fd">

**Comment by mulddang2** [comment]
@April-37 머지 하셨으면 이슈 닫아도 될 것 같습니다!
